print("Welcome to MadLib.py! Please answer the following prompts")
adj1 = input("Please enter an adjective: ")
ani1 = input("Please enter an animal: ")
ver1 = input("Please enter a verb: ")
exc1 = input("Please enter an exclamation: ")
ver2 = input("Please enter another verb: ")
ver3 = input("Please enter another verb: ")
adj2 = input("Please enter another adjective: ")
adv1 = input("Please enter an adverb: ")
adj3 = input("Please enter another adjective: ")
famper1 = input("Please enter the name of a famous person, dead or alive: ")
ver4 = input("Please enter another verb: ")
adv2 = input("Please enter another adverb: ")
ver5 = input("Please enter another verb: ")
plunou1 = input("Please enter a plural noun: ")

print("\nThe other day, I was really in trouble. It all started when I saw a very")
print(adj1.lower() + " " + ani1.lower() + " " + ver1.lower() + " down the hallway. \"" + exc1.capitalize() + "!\" I yelled. But all")
print("I could think to do was to " + ver2.lower() + " over and over. Miraculously,")
print("that caused it to stop, but not before it tried to " + ver3.lower())
print("right in front of my family.\n")
print("What happened next was completely " + adj2.lower() + ". A " + adv1 + " " + adj3 + " " + famper1.title())
print("decided to grace me with their presence.")
print("They " + ver4.lower() + "ed " + adv2.lower() + " and then " + ver5.lower() + "ed right at me. I tried to move but my legs were stuck in " + plunou1.lower() + ".\n")